spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:daom_h2
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql:
        format_sql: true
        default_batch_fetch_size: 500

logging.level:
  org.hibernate.SQL: debug

secret: daom1234

file:
  dir: C:/Users/KBS/Desktop/kbs/Project/daom_upload/