spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:daom_h2
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 500

secret: daom1234